### ISSUE TITLE
Studentensicht: Selbstüberprüfung

### ISSUE THREAD

**Issue by Martinaut** [eTutor-plus-plus/platform#63]
Die Selbstüberprüfung für Studenten ist, zumindest so wie es aktuell umgesetzt ist, nicht wirklich notwendig, sondern kann eher zu Problemen führen. Wenn ein Student aus Versehen "Ja" anstatt "Nein" ankreuzt, werden zu diesem Lernziel keine Aufgaben dem Übungszettel zugeordnet und der Student kann somit die Hausübung nicht absolvieren.

Es ist auch nicht möglich dies nachträglich zu ändern (weder vom Studierenden noch vom Lehrenden).

D.h. aus meiner Sicht wäre es (zumindest derzeit) sinnvoll, die Selbstüberprüfung auszublenden und automatisch alles auf "Nein" zu setzen.

**Comment by kevschuetz** [comment]
Ich hätte es vorerst so gelöst, dass ich den Flag der angibt, ob die Selbstüberprüfung bereits abgeschlossen wurde, im Frontend by-default mit true überschreibe.

Das wäre IMO die einfachste und am leichtesten rückgängig zu machende Lösung.
Sollte keine Nebeneffekte haben, bei der Selbstüberprüfung werden lediglich jene Ziele, die der Student mit "Ja" anklickt, in Fuseki auch als erreicht hinterlegt.
Der Flag wird ansonsten nur verwendet um das anzeigen der Selbstüberprüfung zu bestimmen.

Habe die Änderung mit einem Todo versehen um sie leichter wieder aufzufinden:
![image](https://github.com/eTutor-plus-plus/platform/assets/52571862/b0d46cb9-ef9d-438e-92a3-0a7ddd220956)


https://github.com/eTutor-plus-plus/platform/commit/16451c106dd2001df9b85680bdbd0f95ec970aeb
