### ISSUE TITLE
Studentensicht: Aufgabe - Feedback-Level

### ISSUE THREAD

**Issue by Martinaut** [eTutor-plus-plus/platform#69]
Es ist nicht sehr sinnvoll, wenn man das Feedback-Level völlig frei wählen kann. So könnte man zuerst als Feedback-Level "Viel Feedback auswählen" und später dann vor dem Submit das Feedback-Level auf "Kein Feedback" zurückstellen um keinen Punkteabzug für das Feedback-Level zu erhalten.

Eine Idee wäre, dass sobald ein höhreres Feedback-Level ausgewählt wurde, niedrigere Level deaktiviert werden. Vor der Änderung des Feedback-Levels sollte nochmals eine Warnung angezeigt werden.

**Comment by Martinaut** [comment]
Außerdem wird beim "i"-Popup der Infotext zum Teil abgeschnitten. Hier muss möglicherweise nur der z-index angepasst werden.
![grafik](https://github.com/eTutor-plus-plus/platform/assets/13385585/db0a0b55-6af5-46fe-9691-34269af3d8d3)

**Comment by kevschuetz** [comment]
Das höchste jemals ausgewählte Feedback-Level wird bereits gespeichert und für die Punkteabzüge herangezogen. Deaktivierung niedrigerer Level sollte also einfach realisierbar sein.

**Comment by gruberse** [comment]
Evtl. Warnhinweis, wenn ein Feedback-Level ausgewählt wird, dass Punkte abgezogen werden, wenn Submitted wird.

**Comment by kevschuetz** [comment]
![image](https://github.com/eTutor-plus-plus/platform/assets/52571862/0009ca3b-b06a-4292-afc4-7891af50c778)

Vor der Evaluierung wird nun eine Warnung angezeigt und die Bestätigung des Studenten eingefordert.
Bedingungen:
- Diagnose-Modus
- Gewähltes Level ist > als das jemals zuvor gewählte Level
- Der mögliche Abzug ist > 0 Punkte

**Comment by kevschuetz** [comment]
![image](https://github.com/eTutor-plus-plus/platform/assets/52571862/1841f99c-8904-488c-8f7a-4482e2922e63)

Tooltip wird nun nicht mehr abgeschnitten.

Änderungen siehe:
https://github.com/eTutor-plus-plus/platform/commit/6a18b32b0f72091b91fbbf4ddcf6ffac5f5a930e
