### ISSUE TITLE
Studentensicht: Menü Lernziele

### ISSUE THREAD

**Issue by Martinaut** [eTutor-plus-plus/platform#71]
Wenn man als Student angemeldet ist, wird das Menü "Lernziele" angezeigt, obwohl Studenten hierauf keinen Zugriff haben. Dieser Menüeintrag sollte bei Studenten nicht vorhanden sein.

**Comment by kevschuetz** [comment]
Aktuell gibt es Studenten, Tutoren, LVA-Leiter.
Sollen lediglich LVA-Leiter oder auch Tutoren Zugriff auf das Menü "Lernziele" haben?

**Comment by kevschuetz** [comment]
Menü "Lernziele" wird für Studenten nun nicht mehr angezeigt.
Siehe https://github.com/eTutor-plus-plus/platform/commit/6a338f2f65db86bf8a2b4308fc85d8279f105da9
