### ISSUE TITLE
Rolle: Tutor

### ISSUE THREAD

**Issue by Martinaut** [eTutor-plus-plus/platform#73]
Welche Rechte hat die Tutor-Rolle?
Wie kann man einen Tutor einer Kursinstanz zuordnen?
Was ist, wenn ein Benutzer gleichzeitig die Rollen Tutor und Student hat?
Können Sich Tutoren die Abgaben von Studierenden ansehen?

**Comment by gruberse** [comment]
Kann ein Tutor für Datenmodellierung ein Student in DKE sein (und Lösungen für Übungen einsehen).
