### ISSUE TITLE
Kurs löschen

### ISSUE THREAD

**Issue by Martinaut** [eTutor-plus-plus/platform#80]
Kurse können nicht gelöscht werden.

**Comment by Martinaut** [comment]
Es ist auch nicht möglich einen zugeordneten Übungszettel wieder zu entfernen (z.B. wenn man fälschlicherweise einen Übungszettel zugeordnet hat)

**Comment by kevschuetz** [comment]
Kurse können jetzt gelöscht werden, sofern keine Kursinstanzen zu dem Kurs existieren:
https://github.com/eTutor-plus-plus/platform/commit/243387a8c215074ac3765e5e1d40b9a92a6bf639
