### ISSUE TITLE
Aufgabe erstellen - Layout

### ISSUE THREAD

**Issue by Martinaut** [eTutor-plus-plus/platform#92]
Je nach gewähltem Aufgabentyp muss man sehr viel Scrollen. Das Formular-Layout könnte verbessert werden, indem z.B. nicht nur 50 % der Bildschirmbreite verwendet werden.

**Comment by gruberse** [comment]
Reihenfolge der Formularfelder (z.B. Aufgabentyp und Aufgabenstellung weiter oben, weil wichtig). Felder wie Ersteller und Organisationseinheit sollten automatisch befüllt werden (und ggf. gar nicht angezeigt werden).
