### ISSUE TITLE
Übungszettel Punkteexport

### ISSUE THREAD

**Issue by Martinaut** [eTutor-plus-plus/platform#93]
Es wäre schön, wenn beim Punkteexport eines Übungszettels pro Student eine Zeile zurückgeliefert wird (ähnlich wie bei Moodle).
Aktuell ist es so, dass pro Student und Aufgabe eine Zeile enthalten ist. Schöner wäre es so oder so ähnlich:

* 1. Spalte: Username
* 2. Spalte: Aufgabe 1
* 3. Spalte: Aufgabe 2
* X. Spalte: Aufgabe X
* letzte Spalte: Summe der Punkte

Damit erspart man sich, dass man mit Excel die Punkte pro Student wiederum manuell (bzw. mittels selbst definierter Formeln) ermitteln muss.

**Comment by kevschuetz** [comment]
![image](https://github.com/eTutor-plus-plus/platform/assets/52571862/fa7c6373-fa0c-4393-b4c4-e8144c640475)

CSV-Format wurde standardmäßig umgestellt.
Siehe commit: https://github.com/eTutor-plus-plus/platform/commit/86312e0c3b13959a064c887f7c2a5650146e2447
