### ISSUE TITLE
Klassen aufteilen

### ISSUE THREAD

**Issue by Martinaut** [eTutor-plus-plus/platform#94]
Aktuell ist der Programmcode sehr unübersichtlich; es nicht einfach ersichtlich, wie welche Klassen zusammenarbeiten. Um einen neuen Aufgabentyp hinzuzufügen müssen viele verschiedene Klassen angepasst werden.

Es wäre gut, den Programmcode besser zu modularisieren. So befinden sich bspw. in der Klasse `at.jku.dke.etutor.service.DispatcherProxyResource` Methoden für verschiedenste Aufgabentypen (Datalog, SQL, ...). Es wäre schöner, wenn es hier pro Aufgabentyp eine eigene Klasse geben würde. Analog genauso für alle anderen Klassen (`at.jku.dke.etutor.service.AssignmentSPARQLEndpointService`, `task.model.ts`, ...).

Genauso sollte man sich für Code-Fragemente wie folgendem (aus Klasse `DispatcherProxyService`) eine bessere Lösung einfallen lassen:

```
if (taskType.equals(ETutorVocabulary.BpmnTask.toString())) {
            proxyResource.deleteBpmnExercise(id);
} else if (taskType.equals(ETutorVocabulary.XQueryTask.toString())) {
            proxyResource.deleteXQExercise(id);
} else if (taskType.equals(ETutorVocabulary.SQLTask.toString())) {
            proxyResource.deleteSQLExercise(id);
} else if (taskType.equals(ETutorVocabulary.DatalogTask.toString())) {
            proxyResource.deleteDLGExercise(id);
} else if (taskType.equals(ETutorVocabulary.PmTask.toString())) {
            proxyResource.deletePmExerciseConfiguration(id);
} else if (taskType.equals(ETutorVocabulary.UMLTask.toString())) {
            proxyResource.deleteUMLExercise(id);
}
```

Es ist auch nicht ganz klar, wo (Fuseki, Postgres) welche Daten gespeichert werden.

**Comment by Martinaut** [comment]
Auch so etwas wie [in dieser Zeile](https://github.com/eTutor-plus-plus/dke-dispatcher/blob/1af077e77bb4298420b3cae1349ff702c771fac3/src/main/java/at/jku/dke/etutor/grading/service/SubmissionDispatcherService.java#L67) sollte meiner Meinung nach vermieden werden. Modul-spezifischer Code sollte nur in den jeweiligen Modul-Paketen enthalten sein und "Core"-Code sollte für Module nicht angepasst werden müssen.

**Comment by kevschuetz** [comment]
Siehe https://github.com/eTutor-plus-plus/platform/commit/a469f82768acef000c0fc6e564b6df315fd3e7ae
bezüglich Refactoring in der platform.
